services:
    nginx:
        container_name: todo_nginx
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel-network

    app:
        container_name: todo_app
        build: .
        depends_on:
            - db
        volumes:
            - ./:/var/www
        networks:
            - laravel-network
    db:
        container_name: todo_db
        image: mysql:8
        restart: always
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: to_do
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - todo_db:/var/lib/mysql
        networks:
            - laravel-network

    todo_node:
        container_name: todo_node
        image: node:20
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel-network
        command: bash -c "npm install && npm run dev"

networks:
    laravel-network:
        driver: bridge


volumes:
    todo_db:
